version: '3'
services:
  backend:
    build:
        context: backend
        dockerfile: Dockerfile
    container_name: sp-backend
    image: sp-backend
    environment:
        - SPRING_PROFILES_ACTIVE=prod
        - TZ=Asia/Seoul
    volumes:
        - ./sp_data:/sp_data
    networks:
        - sp-main

  frontend:
    build:
        context: frontend
        dockerfile: Dockerfile
    container_name: sp-frontend
    image: sp-frontend
    ports:
      - "81:80"
    volumes:
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
        - sp-main

networks:
    sp-main:
      name: sp-main

